OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Models/Game.cs
// <copyright file="Game.cs" company="V8K90F">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace GameDataBaseFF.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// This will be used for the Web page to know what properties the game has.
    /// </summary>
    public class Game
    {
        /// <summary>
        /// Gets or Sets the ID of the Game.
        /// </summary>
        [Display(Name = "Game ID")]
        [Required]
        public int ID { get; set; }

        /// <summary>
        /// Gets or Sets the Name of the Game.
        /// </summary>
        [Display(Name = "Name")]
        [Required]
        [StringLength(120, MinimumLength = 1)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets the release date of the Game.
        /// </summary>
        [Display(Name = "Release date")]
        [Required]
        public DateTime ReleaseDate { get; set; }

        /// <summary>
        /// Gets or Sets the price of the Game in HUF.
        /// </summary>
        [Display(Name = "Price")]
        [Required]
        public int Price { get; set; }

        /// <summary>
        /// Gets or Sets the genre of the Game.
        /// </summary>
        [Display(Name = "Game genre")]
        [Required]
        [StringLength(120)]
        public string Genre { get; set; }

        /// <summary>
        /// Gets or Sets the type of the Game.
        /// </summary>
        [Display(Name = "Game type")]
        [Required]
        [StringLength(3, MinimumLength = 2)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets the name of the company who made the Game.
        /// </summary>
        [Display(Name = "Company name")]
        [Required]
        [StringLength(80, MinimumLength = 1)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets the platform where the Game released.
        /// </summary>
        [Display(Name = "Platform name")]
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string PlatformName { get; set; }
    }
}

OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Controllers/GamesController.cs
// <copyright file="GamesController.cs" company="V8K90F">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace GameDataBaseFF.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using GameDataBaseFF.Logic;
    using GameDataBaseFF.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// GamesController class this will be dealing with the requests.
    /// </summary>
    public class GamesController : Controller
    {
        private IDevelopmentLogic logic;
        private IDeviceProduceLogic pLogic;
        private IMapper mapper;
        private GameListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="GamesController"/> class.
        /// </summary>
        /// <param name="logic">Development logic.</param>
        /// <param name="plogic">Deviceproduce logic.</param>
        /// <param name="mapper">Mapper.</param>
        public GamesController(IDevelopmentLogic logic, IDeviceProduceLogic plogic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;
            this.pLogic = plogic;

            this.vm = new GameListViewModel() { EditableGame = new GameDataBaseFF.Web.Models.Game(), ListOfGames = this.mapper.Map<IList<GameDataBaseFF.Data.Game>, List<GameDataBaseFF.Web.Models.Game>>(this.logic.GetAllGames()) };
        }

        /// <summary>
        /// Sends back the main view.
        /// </summary>
        /// <returns>The GAmesIndex page.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "addNew";
            return this.View("GamesIndex", this.vm);
        }

        /// <summary>
        /// Method for details of the games.
        /// </summary>
        /// <param name="id">The gmae id which we want to see.</param>
        /// <returns>Returns the page of a specific game.</returns>
        public IActionResult Details(int id)
        {
            return this.View("GamesDetails", this.GetGameModel(id));
        }

        /// <summary>
        /// Deletes a game from the database.
        /// </summary>
        /// <param name="id">the game we want to delete.</param>
        /// <returns>A page where the game will be deleted.</returns>
        public IActionResult Delete(int id)
        {
            this.TempData["editResult"] = "Delete Failed!";
            if (this.logic.RemoveGame(this.logic.GetOneGame(id)))
            {
                this.TempData["editResult"] = "Delete Succesful!";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Modifies a game.
        /// </summary>
        /// <param name="id">the game id which we want to modify.</param>
        /// <returns>A page where the game will be modified.</returns>
        public IActionResult Modify(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditableGame = this.GetGameModel(id);
            return this.View("GamesIndex", this.vm);
        }

        /// <summary>
        /// The modification of an existing, and adding of a new game.
        /// </summary>
        /// <param name="game">The game we want to modify.</param>
        /// <param name="editAction">Whether we want to modify or create.</param>
        /// <returns>A page with the modified game in the database.</returns>
        [HttpPost]
        public IActionResult Modify(GameDataBaseFF.Web.Models.Game game, string editAction)
        {
            int addableID = 0;
            int paddableID = 0;
            if (this.ModelState.IsValid && game != null)
            {
                if (this.logic.GetAllCompanies().Any(c => c.Name == game.CompanyName))
                {
                    addableID = this.logic.GetAllCompanies().Where(c => c.Name == game.CompanyName).First().Id;
                }

                if (this.pLogic.GetAllPlatforms().Any(p => p.Name == game.PlatformName))
                {
                    paddableID = this.pLogic.GetAllPlatforms().Where(p => p.Name == game.PlatformName).First().Id;
                }

                if (addableID == 0)
                {
                    addableID = 1;
                }

                if (paddableID == 0)
                {
                    paddableID = 1;
                }

                this.TempData["editResult"] = "Nothing Happened!";
                if (editAction == "addNew")
                {
                    try
                    {
                        this.logic.CreateGame(game.Name, game.ReleaseDate, game.Price, game.Genre, game.Type, addableID, paddableID);
                        this.TempData["editResult"] = "Edit Succesful!";
                    }
                    catch (ArgumentException aex)
                    {
                        this.TempData["editResult"] = "Edit Failed!" + aex.Message;
                    }
                }
                else
                {
                    this.TempData["editResult"] = "Else Happened!";
                    if (this.logic.ChangeGame(game.ID, game.Name, game.ReleaseDate, game.Genre, game.Type, game.Price, addableID, paddableID))
                    {
                        this.vm.ListOfGames = this.mapper.Map<IList<GameDataBaseFF.Data.Game>, List<GameDataBaseFF.Web.Models.Game>>(this.logic.GetAllGames());
                        this.TempData["editResult"] = "Edit Succesful!";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditableGame = game;
                return this.View("GamesIndex", this.vm);
            }
        }

        private GameDataBaseFF.Web.Models.Game GetGameModel(int id)
        {
            GameDataBaseFF.Data.Game selected = this.logic.GetOneGame(id);
            return this.mapper.Map<GameDataBaseFF.Data.Game, GameDataBaseFF.Web.Models.Game>(selected);
        }
    }
}

OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Views/Games/GamesDetails.cshtml
@model GameDataBaseFF.Web.Models.Game

@{
    ViewData["Title"] = "Games Details";
}

<h2>Details of the game</h2>

@Html.ActionLink("Go back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.CompanyName)</td>
        <td>@Html.DisplayFor(m => m.CompanyName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PlatformName)</td>
        <td>@Html.DisplayFor(m => m.PlatformName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Genre)</td>
        <td>@Html.DisplayFor(m => m.Genre)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ReleaseDate)</td>
        <td>@Html.DisplayFor(m => m.ReleaseDate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Views/Games/GamesEdit.cshtml
@model GameDataBaseFF.Web.Models.Game

<h2>Edit Game</h2>

@using (Html.BeginForm("Modify", "Games"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.CompanyName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.CompanyName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.PlatformName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.PlatformName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Genre)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Genre)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.ReleaseDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ReleaseDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price) HUF</div>

    <input type="submit" value="Edit" />
}

OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Views/Games/GamesIndex.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model GameDataBaseFF.Web.Models.GameListViewModel

@{
    ViewData["Title"] = "Games Details";
}

<h2>Games Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("GamesEdit", Model.EditableGame)
@await Html.PartialAsync("GamesList", Model.ListOfGames)

OENIK_PROG3_2020_2_V8K90F/GameDataBaseFF.Web/Views/Games/GamesList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<GameDataBaseFF.Web.Models.Game>

<h2>Games List</h2>

@if (Model.Count() == 0)
{
    <p>There's no data that could be shown...</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().CompanyName)</th>
            <th>@Html.DisplayNameFor(m => m.First().Price)</th>
            <th>Datasheet</th>
            <th>Modify</th>
            <th>Delete</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.CompanyName)</td>
                <td>@Html.DisplayFor(m => item.Price) HUF</td>
                <td>@Html.ActionLink("[ SHOW ]", "Details", new { id = item.ID })</td>
                <td>@Html.ActionLink("[ MODIFY ]", "Modify", new { id = item.ID })</td>
                <td>@Html.ActionLink("[ DELETE ]", "Delete", new { id = item.ID })</td>
            </tr>
        }
    </table>
}